# -*- coding: utf-8 -*-
"""implied_volatility_and_options_plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2df-8aKdFRHRcHcdExMdDwt5G0ZDL7B
"""

# region imports
from AlgorithmImports import *
# endregion

class WellDressedAsparagusSnake(QCAlgorithm):

    def initialize(self):
        self.set_start_date(2020, 1, 1)
        self.set_cash(100000)

        self.equity = self.add_equity("GME", Resolution.DAILY, data_normalization_mode=DataNormalizationMode.Raw)
        self.option = self.add_option("GME", Resolution.DAILY)
        self.option.set_filter(timedelta(0), timedelta(30))

        # Gráfico personalizado solo con Delta, PrecioPrima y VolumenOpc (Open Interest no está disponible directamente)
        chart = Chart("AnalisisOpciones")
        chart.add_series(Series("IV", SeriesType.LINE, 0))
        chart.add_series(Series("PrecioPrima", SeriesType.LINE, 1))
        chart.add_series(Series("VolumenOpc", SeriesType.LINE, 2))  # Esto representa volumen, no open interest
        self.add_chart(chart)

    def on_data(self, data: Slice):
        if not data.option_chains:
            return

        for chain in data.option_chains.values():
            contracts = sorted(chain, key=lambda x: x.volume, reverse=True)
            if not contracts:
                continue

            contract = contracts[0]  # Contrato con mayor volumen

            if contract.implied_volatility is not None:
                self.plot("AnalisisOpciones", "IV", contract.implied_volatility)

            if contract.last_price is not None:
                self.plot("AnalisisOpciones", "PrecioPrima", contract.last_price)

            if contract.volume is not None:
                self.plot("AnalisisOpciones", "VolumenOpc", contract.volume)

            # Lógica de trading basada en IV
            if self.portfolio.invested:
                if contract.implied_volatility < 0.10:
                    self.liquidate("GME")
                    self.debug(f"Cierre: Fecha={self.time}, Volatilidad Implicita={contract.implied_volatility}")
            else:
                if contract.implied_volatility > 0.50:
                    self.set_holdings("GME", 1)
                    self.debug(f"Apertura: Fecha={self.time}, Volatilidad Implicita={contract.implied_volatility}")