# -*- coding: utf-8 -*-
"""seasonal_month.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKs2r0DHGKWfkH9BOCiLY6olTTNOgQIa
"""

# region imports
from AlgorithmImports import *
# endregion

class NVAXSeasonalStrategy(QCAlgorithm):
    def initialize(self):
        self.set_start_date(2004, 1, 1)  # Inicio en 2004
        self.set_cash(100000)  # Capital inicial
        self.symbol = self.add_equity("NVAX", Resolution.HOUR, data_normalization_mode=DataNormalizationMode.Raw).symbol  # Agregar NVAX en 1 hora
        self.Securities[self.symbol].SetFeeModel(ConstantFeeModel(0))

    def on_data(self, data: Slice):
        if not data.bars.contains_key(self.symbol):
            return  # Salir si no hay datos

        month = self.time.month

        # Comprar 10% del portafolio en abril si no hay posiciones abiertas
        if month == 4 and not self.portfolio[self.symbol].invested:
            self.set_holdings(self.symbol, 1)

        # Vender todo en septiembre
        if month == 9 and self.portfolio[self.symbol].invested:
            self.liquidate(self.symbol)