# -*- coding: utf-8 -*-
"""seasonal_day_of_month.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udUZ0DDwtfqms88maeiHS-QSFCUGfB4B
"""

# region imports
from AlgorithmImports import *
# endregion

class NVAXSeasonalStrategy(QCAlgorithm):
    def initialize(self):
        self.set_start_date(2004, 1, 1)  # Inicio en 2004
        self.set_cash(100000)  # Capital inicial
        self.symbol = self.add_equity("NVAX", Resolution.HOUR, data_normalization_mode=DataNormalizationMode.Raw).symbol  # Agregar NVAX en 1 hora
        self.Securities[self.symbol].SetFeeModel(ConstantFeeModel(0))

    def on_data(self, data: Slice):
        if not data.bars.contains_key(self.symbol):
            return  # Salir si no hay datos

        day = self.time.day

        # Comprar 100% del portafolio los días 10 y 29 si no hay posiciones abiertas
        if day in [10, 29] and not self.portfolio[self.symbol].invested:
            self.set_holdings(self.symbol, 1)

        # Vender todo al siguiente día
        if day not in [10, 29] and self.portfolio[self.symbol].invested:
            self.liquidate(self.symbol)