# -*- coding: utf-8 -*-
"""seasonal_weekday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlhWMkjexTOGlzAZqiNK8SIvEOAhQqRy
"""

# region imports
from AlgorithmImports import *
# endregion

class NVAXMondayOnlyStrategy(QCAlgorithm):
    def initialize(self):
        self.set_start_date(2004, 1, 1)  # Inicio en 2004
        self.set_cash(100000)  # Capital inicial
        self.symbol = self.add_equity("NVAX", Resolution.HOUR, data_normalization_mode=DataNormalizationMode.Raw).symbol  # Agregar NVAX en 1 hora
        self.Securities[self.symbol].SetFeeModel(ConstantFeeModel(0))

    def on_data(self, data: Slice):
        if not data.bars.contains_key(self.symbol):
            return  # Salir si no hay datos

        weekday = self.time.weekday()  # Obtener el día de la semana (0 = Lunes, 6 = Domingo)

        # Comprar 10% del portafolio solo los lunes si no hay posiciones abiertas
        if weekday == 0 and not self.portfolio[self.symbol].invested:
            self.set_holdings(self.symbol, 1)

        # Liquidar la posición cualquier otro día de la semana
        if weekday != 0 and self.portfolio[self.symbol].invested:
            self.liquidate(self.symbol)